# Permalinks
permalink:      /academic/:year-:month-:day/:title

# Setup
title:          academic
paginate:       5
baseurl:        /academic
url:            "https://j-faria.github.io/academic"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         João Faria
  url:          https://astro.up.pt/~jfaria
  email:        joao.faria@astro.up.pt

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/j-faria/academic

plugins:
  - jekyll-paginate
